# frozen_string_literal: true

class Roles
  PUBLIC_USER = 'PUBLIC_USER'
  PUBLIC_USER_PRIVILEGE_LEVEL = 0
  NUS_USER = 'NUS_USER'
  NUS_USER_PRIVILEGE_LEVEL = 1
  MOD_USER = 'MOD_USER'
  MOD_USER_PRIVILEGE_LEVEL = 2
  ADMIN = 'ADMIN'
  ADMIN_PRIVILEGE_LEVEL = 3
  Enums = {
      'PUBLIC_USER': PUBLIC_USER,
      'NUS_USER': NUS_USER,
      'MOD_USER': MOD_USER,
      'ADMIN': ADMIN
  }.freeze
  PRIVILEGE_LEVEL = {
      'PUBLIC_USER': PUBLIC_USER_PRIVILEGE_LEVEL,
      'NUS_USER': NUS_USER_PRIVILEGE_LEVEL,
      'MOD_USER': MOD_USER_PRIVILEGE_LEVEL,
      'ADMIN': ADMIN_PRIVILEGE_LEVEL
  }.freeze
end
