version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    volumes:
    - .:/app
    command: ["./scripts/start.sh"]
    network_mode: "host"
    ports:
      - "80:80"
